package proxy;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;

import proxy.InvocationHandler;
import proxy.ProxyGenerator;

public class AsmProxyGenerator extends ProxyGenerator {
  // Automatically increments on every call of genearateProxyClass();
  protected static int classId = 0;

  // ClassLoader to load class from generated byte[].
  private static ProxyClassLoader classLoader = new ProxyClassLoader();

  @Override
  protected String proxyClassNamePrefix() {
    return "AsmProxyClass";
  }

  public Class<?> generateProxyClass(Class<?>[] interfaces) {
    ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_MAXS);

    // Generate type names, note that all "." in class path are replaced by "/".
    //
    // Class name.
    String proxyClassName =
        ProxyGenerator.PACKAGE_NAME + "/" + proxyClassNamePrefix() + String.valueOf(classId++);
    // Interface names.
    String[] interfaceNames = new String[interfaces.length];
    for (int i = 0; i < interfaces.length; i++) {
      interfaceNames[i] = interfaces[i].getName().replace(".", "/");
    }

    // Create a new class.
    cw.visit(Opcodes.V1_8,  // java version: v1.8
             Opcodes.ACC_PUBLIC,  // access flags
             proxyClassName,  // class name
             null,  // signature
             "java/lang/Object",  // super class
             interfaceNames);  // interface names

    // Add field:
    //   private InvocationHandler handler;
    cw.visitField(Opcodes.ACC_PRIVATE,  // access flags
                  "handler",  // field name
                  Type.getDescriptor(InvocationHandler.class),  // field type
                  null,  // signature
                  null).visitEnd();  // default value
    // Add field:
    //   private java.util.HashMap<String, java.lang.reflect.Method> proxyMethods;
    cw.visitField(Opcodes.ACC_PRIVATE,  // access flags
                  "proxyMethods",  // field name
                  Type.getDescriptor(HashMap.class),  // field type
                  null,  // signature
                  null).visitEnd();  // default value

    // Add constructor.
    addConstructor(cw, proxyClassName);


    try {
      // Add method initMethodFields().
      addInitMethod(cw, proxyClassName, interfaces);

      // Add proxy methods.
      addProxyMethods(cw, proxyClassName, interfaces);
    } catch (NoSuchMethodException e) {
      e.printStackTrace();
      return null;
    }

    cw.visitEnd();
    byte[] data = cw.toByteArray();

    // Write class data to file.
    try {
      File file = new File("/home/hy/Desktop/Proxy.class");
      FileOutputStream fout = new FileOutputStream(file);
      fout.write(data);
      fout.close();
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }

    Class<?> clazz = classLoader.defineClassForName(proxyClassName.replace("/", "."), data);
    return clazz;
  }

  // Constructor source code:
  //
  // public hyproxygen.ProxyClass(InvocationHandler handler) {
  //   this.handler = handler;
  //   this.proxyMethods = new java.util.HashMap<String, java.lang.reflect.Method>();
  //   this.initMethodFields();
  // }
  //
  // Byte code:
  //   0: aload_0
  //   1: invokespecial #1                  // Method java/lang/Object."<init>":()V
  //   4: aload_0
  //   5: aload_1
  //   6: putfield      #2                  // Field handler:Lproxy/InvocationHandler;
  //   9: aload_0
  //  10: new           #3                  // class java/util/HashMap
  //  13: dup
  //  14: invokespecial #4                  // Method java/util/HashMap."<init>":()V
  //  17: putfield      #5                  // Field proxyMethods:Ljava/util/HashMap;
  //  20: aload_0
  //  21: invokevirtual #6                  // Method initMethodFields:()V
  //  24: return
  //
  private boolean addConstructor(ClassWriter cw, String proxyClassName) {
    MethodVisitor constructor = cw.visitMethod(Opcodes.ACC_PUBLIC,
                                               "<init>",
                                               "(Lproxy/InvocationHandler;)V",
                                               null, null);
    constructor.visitVarInsn(Opcodes.ALOAD, 0);
    constructor.visitMethodInsn(Opcodes.INVOKESPECIAL,
                                "java/lang/Object",
                                "<init>",
                                "()V",
                                /* is interface = */false);
    
    // source: this.handler = handler;
    constructor.visitVarInsn(Opcodes.ALOAD, 0);
    constructor.visitVarInsn(Opcodes.ALOAD, 1);
    constructor.visitFieldInsn(Opcodes.PUTFIELD,
                               proxyClassName,
                               "handler",
                               Type.getDescriptor(InvocationHandler.class));

    // source: this.proxyMethods = new java.util.HashMap<String, java.lang.reflect.Method>();
    constructor.visitVarInsn(Opcodes.ALOAD, 0);
    constructor.visitTypeInsn(Opcodes.NEW, "java/util/HashMap");
    constructor.visitInsn(Opcodes.DUP);
    constructor.visitMethodInsn(Opcodes.INVOKESPECIAL,
                                "java/util/HashMap",
                                "<init>",
                                "()V",
                                /* is interface = */false);
    constructor.visitFieldInsn(Opcodes.PUTFIELD,
                               proxyClassName,
                               "proxyMethods",
                               Type.getDescriptor(java.util.HashMap.class));

    // source: this.initMethodFields();
    constructor.visitVarInsn(Opcodes.ALOAD, 0);
    constructor.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                                proxyClassName,
                                "initMethodFields",
                                "()V",
                                /* is interface = */false);

    constructor.visitInsn(Opcodes.RETURN);
    constructor.visitMaxs(1, 1);
    constructor.visitEnd();
    return true;
  }

  private boolean addInitMethod(ClassWriter cw, String proxyClassName, Class<?>[] interfaces) 
      throws NoSuchMethodException {
    MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PRIVATE,
                                      "initMethodFields",
                                      "()V",
                                      null, null);

    for (Class ifc : interfaces) {
      // source: clazz = Class.forName("xx.xxx");
      mv.visitLdcInsn(ifc.getName());
      mv.visitMethodInsn(Opcodes.INVOKESTATIC,
                         "java/lang/Class",
                         "forName",
                         Type.getMethodDescriptor(Class.class.getMethod("forName",String.class)),
                         /* is interface = */false);
      mv.visitVarInsn(Opcodes.ASTORE, 1);  // var1 = clazz
      mv.visitVarInsn(Opcodes.ALOAD, 1);

      // source:
      //   for (java.lang.reflect.Method method : clazz.getMethods()) {
      //     proxyMethods.put(method.toString(), method);
      //   }
      mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                         "java/lang/Class",
                         "getMethods",
                         Type.getMethodDescriptor(Class.class.getMethod("getMethods")),
                         /* is interface = */false);
      mv.visitVarInsn(Opcodes.ASTORE, 2);  // var2 = methods = clazz.getMethods()
      mv.visitVarInsn(Opcodes.ALOAD, 2);

      mv.visitInsn(Opcodes.ARRAYLENGTH);
      mv.visitVarInsn(Opcodes.ISTORE, 3);  // var3 = methods.length
      mv.visitInsn(Opcodes.ICONST_0);
      mv.visitVarInsn(Opcodes.ISTORE, 4);  // var4 = i

      // Start for loop.
      mv.visitVarInsn(Opcodes.ILOAD, 4);
      mv.visitVarInsn(Opcodes.ILOAD, 3);
    }


    mv.visitInsn(Opcodes.RETURN);
    mv.visitMaxs(1, 1);
    mv.visitEnd();

    return true;
  }

  private boolean addProxyMethods(ClassWriter cw, String proxyClassName, Class<?>[] interfaces) {
    return true;
  }

  private static class ProxyClassLoader extends ClassLoader {
    public ProxyClassLoader() {
      super(Thread.currentThread().getContextClassLoader());
    }
 
    public Class<?> defineClassForName(String name, byte[] data) {
      return this.defineClass(name, data, 0, data.length);
    }
  }
}
